name: Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Docker
        uses: docker/setup-buildx-action@v2

      - name: Логін у DockerHub (опційно)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Збірка Docker-образів
        run: docker-compose -f docker-compose.yml build

      - name: (Опційно) Запуск тестів
        run: echo "No tests configured"

      - name: Деплой на Railway
        run: |
          npm install -g @railway/cli
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
